### ISSUE TITLE
help

### ISSUE THREAD

**Issue by LetMeJustDoThis** [Oreeeee/yokkaichi#2]
so ive tried the bot ive installed all the packages and i got errors i fixed them but i really dont know what i should put here
![image](https://user-images.githubusercontent.com/105584635/202925014-ab5e8fd9-4867-419c-a282-f12f1ab6f9c5.png)

**Comment by Oreeeee** [comment]
You have to put a location to a file called `IP2LOCATION-LITE-DB1.BIN` that you downloaded from https://lite.ip2location.com/. You can just skip the `-c/--check-country` argument, but the location of the server won't show up in the results file. The file isn't required to run this script!
